version: '3.4'

#create a volume for the my sql container.To ensure Data persists after my sql container is stopped
volumes:
  datafiles:

services:
  #DataBase Service
  database:
    image: mysql:8.0.25
    ports:
      - "3306:3306"
    volumes:
      - datafiles:/var/lib/mysql
      - "/Users/eduardobarron/Projects/QUETZAL/NetCoreAPI-InDocker/API/sql-scripts/setup.sql:/docker-entrypoint-initdb.d/1.sql"
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: newuser
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: test
  #Api  Service
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: API/Dockerfile
    depends_on: 
      - database
    ports:
      - "5000:80"
    restart: always
    environment: 
      - DBHOST=database
      - DBPORT=3306
      - ASPNETCORE_ENVIRONMENT=Development
